AjouCola/FE-CLIENT

src/components/Layout.tsx
src/components/atoms/sidebar/index.ts
src/components/molecules/header/index.tsx
src/components/molecules/header/styles.tsx
src/components/molecules/sidebar/index.tsx
src/components/molecules/sidebar/styles.tsx
src/pages/_app.tsx
src/pages/board/index.tsx
src/pages/board/styles.tsx
src/pages/login/index.tsx
src/pages/signup/index.tsx
src/pages/signup/styles.ts
src/pages/todomate/index.tsx
src/pages/write/index.tsx
src/pages/write/styles.ts
src/utils/api/main.ts

-  회원가입 및 로그인 양식 수정
-  라우팅 페이지 추가
-  사이드바 추가
-  로그인 시에는 required 속성만 검사하면 되기 때문에 이외의 유효성 검사 삭제함.
-  회원가입 양식 스타일 수정 및 이메일 인증 버튼 추가
- 사이드바 추가하여 현재 이동할 수 있는 페이지를 연결해 두었습니다.
- 사이드바는 recoil을 이용하여 관리하며 sidebar 상태에 따라 selector를 이용해 사이드바의 display 유무를 결정하도록 구현하였습니다.
- 사이드바를 어떻게 관리할 지에 대해서 더 나은 방향이 있다면 알려주시길 부탁드리겠습니다 ㅎㅎ

Feat : Modify sign in and sign up forms and Add side bar menu

---

public/all.svg
public/all_check.svg
public/edit.svg
public/edit_check.svg
public/preview.svg
public/preview_check.svg
src/components/Layout.tsx
src/components/atoms/button/submit.tsx
src/components/atoms/hashtagChip/index.tsx
src/components/atoms/hashtagChip/styles.tsx
src/components/atoms/input/index.tsx
src/components/molecules/editor/styles.tsx
src/components/molecules/previewer/index.tsx
src/components/molecules/previewer/styles.tsx
src/components/organisms/Navigation/index.tsx
src/components/organisms/markdowneditor/styles.tsx
src/components/templates/signUp/index.tsx
src/components/templates/write/index,type.ts
src/components/templates/write/index.tsx
src/components/templates/write/styles.ts
src/styles/theme.ts
yarn.lock

- 디자인에 따른 글쓰기 페이지 수정
- media 태그를 사용한 반응형 디자인
- 디자인에 따른 해시태그 변경
- 해시태그에서 글씨가 특정 길이를 넘는경우 ..으로 처리하였습니다.
- 개발자 도구에서 제공하는 표준 px로 breakpoint를 나눴습니다.
글쓰기 페이지는 grid와 media를 통해 모바일&태블릿 사이즈이면 해시태그바가 내려가게 구현하였습니다.

[refactor] write UI

---

src/pages/board/[id].tsx
src/pages/board/index.tsx
src/pages/mypage/index.tsx
src/pages/signIn/index.tsx
src/pages/signUp/index.tsx
src/pages/todolist/index.tsx
src/pages/write/index.tsx

각 페이지 컴포넌트에 NextPage 타입 명시
-  각 페이지에 NextPage 타입 명시
- 
-

[Refactoring] Add NextPage type in each pages

---

src/components/atoms/hashtagChip/styles.tsx
src/components/organisms/boardContent/index.tsx
src/components/organisms/boardContent/styles.ts
src/pages/board/[id].tsx

- 해시태그 바 스타일 수정
- 해시태그 small 사이즈 min-width 설정
- 해시태그바 render 되는 아이템 설정
- 스크롤이 아니라 버튼형식으로 일단 구현되어있습니다.
- 스크롤 하려면 수정해야합니다!

[Style] board content

---

src/components/molecules/searchBar/index.tsx
src/components/molecules/searchBar/styles.tsx

- 드롭다운 검색창 스타일 적용
- Input컴포넌트의 focus 여부에 따라 box-shadow 및 border-radius 속성 조절
- SearchModal 컴포넌트 분리 및 검색어 기록, 컨트롤러 wrapper 추가
- 추후 아이콘 적용 하겠습니다.
- 코드 정리 추후에 올리겠습니다.

[Style] 드롭다운 검색창 스타일

---

src/assets/icon/folder_primary.svg
src/assets/icon/left_arrow_primary.svg
src/assets/icon/right_arrow_primary.svg
src/components/Layout.tsx
src/components/atoms/calenderDayElement/index.tsx
src/components/atoms/calenderDayElement/styles.tsx
src/components/atoms/todoCheckBox/draggable.tsx
src/components/atoms/todoCheckBox/index.tsx
src/components/atoms/todoCheckBox/styles.tsx
src/components/molecules/calender/index.tsx
src/components/molecules/calender/styles.tsx
src/components/molecules/todoArea/index.tsx
src/components/molecules/todoArea/styles.ts
src/components/molecules/todoMenuModal/index.tsx
src/components/molecules/todoMenuModal/styles.tsx
src/pages/todolist/index.tsx
src/store/index.ts
src/store/todo.ts
src/styles/todolist/index.ts

- 투두리스트 페이지 스타일 적용
- 투두리스트 수정 기능
- 캘린더 수정
- 투두리스트 아이템 수정
- 아이콘 등은 추후 적용하겠습니다.
- 아직 데이터 저장은 되지 않습니다.

[Feat] TodoList 페이지

---

.eslintrc.json
.prettierrc.json
package.json
src/components/atoms/button/index.tsx
src/components/organisms/signUpForm/index.type.ts
yarn.lock

[Hotfix] change endOfLine rule and lint code

---

src/pages/todolist/index.tsx
src/store/index.ts
src/utils/api/Todo.ts

- todo list api연동을 위한 구조 변경
- 
-

feat: add skeleton code for todo list api

---

src/components/molecules/homeBoardItem/styles.ts

- eslint error 해결
- import order 수정
-

[hotfix] lint code

---

src/components/atoms/calenderDayElement/index.tsx
src/components/atoms/calenderDayElement/styles.tsx
src/components/atoms/doneImg/index.tsx
src/components/molecules/calender/styles.tsx
src/components/organisms/homeSection/boardSection.tsx
src/components/organisms/homeSection/todoSection.tsx
src/pages/index.tsx

[Style] 메인 반응형 UI

---

src/assets/icon/notify.svg
src/components/molecules/header/index.tsx
src/components/molecules/header/styles.tsx
src/components/molecules/profileDropdownItem/index.tsx
src/components/molecules/profileDropdownItem/styles.ts
src/components/molecules/profileDropdownTab/index.tsx
src/components/molecules/profileDropdownTab/styles.ts
src/components/organisms/Navigation/index.tsx
src/components/organisms/profileDropdown/index.tsx
src/components/organisms/profileDropdown/styles.ts
src/utils/api/Auth.ts

- 프로필 드롭다운 메뉴 스타일 적용
- 프로필 드롭다운 메뉴 스타일
-

style: add profile dropdown menu

---

src/components/molecules/header/index.tsx
src/components/molecules/header/styles.tsx
src/components/molecules/modal/mobileSearchModal.tsx
src/components/molecules/searchBar/index.tsx
src/components/molecules/searchBar/styles.tsx
src/components/molecules/sidebar/styles.tsx
src/components/organisms/notifyDropdown/index.tsx
src/components/organisms/notifyDropdown/styles.ts
src/constants/index.tsx

- 헤더 반응형 스타일 추가
- 프로필 메뉴 삭제
- 로그인 시에 만 사용
- 알림 메뉴 추가
-

[Style] 헤더 반응형 스타일 추가

---

src/components/Layout.tsx
src/components/organisms/homeSection/boardSection.tsx

- 네비게이션 조건 및 props 이름 변경
- on이라는 props 이름으로 설정 시 boolean을 넘겨주면 warning이 발생하여 변경
-

[Style] 네비게이션 조건 및 props 이름 변경

---

src/components/organisms/markdownEditor/index.tsx
src/pages/write/index.tsx
src/utils/api/Board.ts
src/utils/api/core/index.ts

- 게시글 API 모듈 생성 및 게시글 작성 API 연동
- Board Api
- create Post
-

[Feat] 게시글 API 모듈 생성 및 게시글 작성 API 연동

---

src/pages/board/[id].tsx

[Hotfix] 테스트 게시글 ID 추가

---

src/components/atoms/button/auth.tsx
src/components/organisms/signUpForm/index.tsx
src/components/organisms/signUpInput/index.tsx
src/components/organisms/signUpInput/styles.tsx

- 회원가입 페이지 이메일 로딩 스피너 추가
- 이메일 로딩 스피너 추가
- 이메일 인증코드 요청 시 응답 받은 후 인증번호 입력칸 나오도록 되어있던 것에서 사용자 경험을 위해 일단 띄우도록 변경
-

[Style] 회원가입 페이지 이메일 로딩 스피너 추가

---

src/pages/board/index.tsx
src/pages/redirect.tsx
src/utils/api/Board.ts

- 게시글 불러오기 API 추가
- Board API getList() 추가
-  page는 0부터 시작
- useInfiniteQuery 함수 도입
- useInfiniteQuery를 위해서 많은 테스트가 필요할 것 같습니다. 로컬에서 API 테스트가 안되기 때문에 merge를 자주 해야할 것 같네요
-

[Feat] 게시글 불러오기 API 추가

---

src/assets/icon/board_detail_type.svg
src/assets/icon/board_grid_type.svg
src/assets/icon/board_list_type.svg
src/components/organisms/boardPageTemplate/index.tsx
src/components/organisms/signUpInput/styles.tsx
src/styles/board/index.ts
src/styles/globals.css

- 게시판 스타일 수정
- 게시판 헤더 스타일 설정
- 게시판 제목 스타일
- 게시판 정렬 및 타입 버튼 스타일
- 글쓰기 버튼 스타일
- 게시글 리스트 스탕리 수정
- 로딩 스피너 추가
-

[Style] 게시글 리스트 스타일 수정

---

src/components/molecules/editor/CommentViewer.tsx
src/pages/board/[id].tsx
src/utils/api/Comment.ts

- 댓글 삭제 API 연동
- 자신의 댓글에만 메뉴 버튼 보이도록 설정
- 댓글 delete API 추가
-

[Feat] 댓글 삭제 기능 추가

---

package-lock.json
src/components/molecules/todoProgress/index.tsx
src/components/organisms/homeSection/todoSection.tsx
yarn.lock

-ProgressItem 구현
- 프로그레스 바 구현
-

ProgressItem 구현

---

src/components/molecules/todoProgress/index.tsx
src/components/organisms/homeSection/todoSection.tsx

feat:implement progressBar animation

---

src/components/molecules/todoProgress/index.tsx
src/components/organisms/homeSection/todoSection.tsx

feat: represent progress bar weekly form

---

src/components/organisms/signUpForm/index.tsx

- console.log 삭제 
- 
- 코드리뷰를 위한 PR

refactor: delete console log

---

src/components/atoms/calenderDayElement/index.tsx
src/components/atoms/card/index.tsx
src/components/atoms/folderItem/index.tsx
src/components/molecules/boardType/boardCard/index.tsx
src/components/molecules/boardType/boardPreviewItem/index.tsx
src/components/molecules/boardType/boardSimpleItem/index.tsx
src/components/molecules/calender/index.tsx
src/components/molecules/todoArea/index.tsx
src/components/molecules/todoContent/edit.tsx
src/components/molecules/todoContent/index.tsx
src/pages/index.tsx
src/pages/mypage/index.tsx

- img => Image 교체
- 각종 코드 리팩토링
- Image 컴포넌트 적용
- console.log 삭제
- 여러 로직 분리
- 코드의 가독성을 위해 로직을 여러 함수로 분리하려고 시도했습니다. 
- 약간의 타입 수정
- 현재 파악할 수 있는 부분 타입 수정 
- 추가적으로 계속해서 진행해야할 것 같습니다. 서버가 닫혀있는 상태로 로그인도 안되고 데이터도 불러올 수 없어서 코드만 읽고 리팩토링하고 있는데 어려움이 많습니다. 추후에 간단한 mock server 구성해서 리팩토링 해보면 좋을 것 같아요

프로젝트 코드 리팩토링
